apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to my Kubernetes</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          background-color: #f4f4f4;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          color: #333;
        }
        .container {
          text-align: center;
          background-color: #fff;
          padding: 50px;
          border-radius: 8px;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        h1 {
          color: #5c6bc0;
        }
        p {
          font-size: 18px;
          color: #666;
        }
        .btn {
          padding: 10px 20px;
          font-size: 16px;
          background-color: #5c6bc0;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          margin-top: 20px;
          transition: background-color 0.3s;
        }
        .btn:hover {
          background-color: #3f4a88;
        }
      </style>
    </head>
    <body>

      <div class="container">
        <h1>Welcome to my Kubernetes Cluster</h1>
        <p>This is a simple webpage hosted in a Kubernetes cluster using a ConfigMap.</p>
        <button class="btn" onclick="handleClick()">Click Me</button>
      </div>

      <script>
        function handleClick() {
          alert('Kubernetes is fabulous!');
          window.location.href = 'https://www.eltiempo.es/taxonera-colegio.html';
        }
      </script>

    </body>
    </html>
