apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # or your desired namespace
  source:
    repoURL: https://github.com/jhidalgo90/argo-app1.git
    targetRevision: main
    path: app1  # This is the folder containing your manifests
  project: argo-app1
